## Program1

In [53]:
import csv

with open('enjoysport.csv', 'r') as file:
    data = [row for row in csv.reader(file)]
    print("The total number of instances are : ", len(data)-1, '\n', data[1:])

num_attributes = len(data[0])-1

hypothesis = ['0']*num_attributes

for i in range(0, len(data)):
    if data[i][num_attributes] == 'yes':
        for j in range(0, num_attributes):
            if hypothesis[j] == '0' or hypothesis[j] == data[i][j]:
                hypothesis[j] = data[i][j]
            else:
                hypothesis[j] = '?'
    print("the hypothesis for the training instances {} is: \n" .format(i),hypothesis)
print("Maximally specific hypothesis for the training instances are : \n", hypothesis)

The total number of instances are :  4 
 [['sunny', 'warm', 'normal', 'strong', 'warm', 'same', 'yes'], ['sunny', 'warm', 'high', 'strong', 'warm', 'same', 'yes'], ['rainy', 'cold', 'high', 'strong', 'warm', 'change', 'no'], ['sunny', 'warm', 'high', 'strong', 'cool', 'change', 'yes']]
the hypothesis for the training instances 0 is: 
 ['0', '0', '0', '0', '0', '0']
the hypothesis for the training instances 1 is: 
 ['sunny', 'warm', 'normal', 'strong', 'warm', 'same']
the hypothesis for the training instances 2 is: 
 ['sunny', 'warm', '?', 'strong', 'warm', 'same']
the hypothesis for the training instances 3 is: 
 ['sunny', 'warm', '?', 'strong', 'warm', 'same']
the hypothesis for the training instances 4 is: 
 ['sunny', 'warm', '?', 'strong', '?', '?']
Maximally specific hypothesis for the training instances are : 
 ['sunny', 'warm', '?', 'strong', '?', '?']


## Program 2

In [187]:
import pandas as pd

In [189]:
data = pd.read_csv('enjoysport.csv')
concepts = data.iloc[:,:-1].values
target = data.iloc[:,-1].values
n = len(concepts[0])-1
specific_h = ['0']*n
generic_h = ['0']*n
print("S0: ", specific_h, "\n G0: ", generic_h)

S0:  ['0', '0', '0', '0', '0'] 
 G0:  ['0', '0', '0', '0', '0']


In [199]:
def learn(concepts, target):
    specific_h = concepts[0].copy()
    generic_h = [['?' for _ in range(len(specific_h))] for _ in range(len(specific_h))]

    for i, h in enumerate(concepts):
        if target[i] == 'yes':
            print(f"{i+1} training instance is positive:", concepts[i])
            for x in range(len(specific_h)):
                if h[x] != specific_h[x]:
                    specific_h[x] = '?'
                    generic_h[x][x] = '?'
        else:
            print(f"{i+1} training instance is negative:", concepts[i])
            for x in range(len(specific_h)):
                if h[x] != specific_h[x]:
                    generic_h[x][x] = specific_h[x]
                else:
                    generic_h[x][x] = '?'
        print(f"s{i+1}:\n", specific_h)
        print(f"g{i+1}:\n", generic_h)

    generic_h = [h for h in generic_h if h != ['?' for _ in range(len(specific_h))]]
    return specific_h, generic_h

In [201]:
s_final, g_final = learn(concepts, target)
print("The final specific hypothesis:")
print(s_final)
print("The final generic hypothesis:")
print(g_final)

1 training instance is positive: ['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
s1:
 ['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
g1:
 [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]
2 training instance is positive: ['sunny' 'warm' 'high' 'strong' 'warm' 'same']
s2:
 ['sunny' 'warm' '?' 'strong' 'warm' 'same']
g2:
 [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]
3 training instance is negative: ['rainy' 'cold' 'high' 'strong' 'warm' 'change']
s3:
 ['sunny' 'warm' '?' 'strong' 'warm' 'same']
g3:
 [['sunny', '?', '?', '?', '?', '?'], ['?', 'warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'same']]


## Program 3

In [62]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import export_graphviz
from sklearn.preprocessing import LabelEncoder
import graphviz

In [88]:
data = pd.read_csv('id3.csv')
df = pd.DataFrame(data)

label_encoder = LabelEncoder()
for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = label_encoder.fit_transform(df[column])

x = df.drop('PlayTennis', axis = 1)
y = df['PlayTennis']

clf  =  DecisionTreeClassifier(criterion = 'entropy')

clf.fit(x,y)

dot_data = export_graphviz(clf, out_file = None , feature_names = x.columns, class_names = label_encoder.classes_, rounded=True, node_ids = True, filled = True, special_characters = True)
graph = graphviz.Source(dot_data)
graph.view()

'Source.gv.pdf'

## Program 4

In [212]:
# 6361337284
import numpy as np
x = np.array(([2,9], [1,5], [3,6]),dtype = float)
y = np.array(([92], [89], [86]), dtype=float)
x = x/np.amax(x, axis=0)
y=y/100

#sigmoid function
def sigmoid(x):
    return 1/ (1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1-x)

epoch = 5000
lr = 0.1
inputlayer_neuron = 2
hiddenlayer_neuron = 3
outputlayer_neuron = 1


In [216]:
wh = np.random.uniform(size=(inputlayer_neuron, hiddenlayer_neuron))
bh = np.random.uniform(size=(1, hiddenlayer_neuron))
wout = np.random.uniform(size=(hiddenlayer_neuron, outputlayer_neuron))
bout = np.random.uniform(size = (1, outputlayer_neuron))

for i in range(epoch):
   #forward propogation
    hinp1 = np.dot(x,wh)
    hinp = hinp1+bh
    hlayer_act =  sigmoid(hinp)
    outinp1 = np.dot(hlayer_act, wout)
    outinp = outinp1+bout
    output = sigmoid(outinp)

    #backward propogation
    E0 = y - output
    outgrad = derivatives_sigmoid(output)
    d_output = E0*outgrad
    EH = d_output.dot(wout.T) 

    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad

    wout += hlayer_act.T.dot(d_output) *lr
    wh += x.T.dot(d_hiddenlayer) *lr

print("Input: \n" + str(x)) 
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.89]
 [0.86]]
Predicted Output: 
 [[0.89759413]
 [0.88143758]
 [0.88955898]]


## Program 5

In [90]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [110]:
df = pd.read_csv('pima_indian.csv')

#define feature names and columns
feature_col_names = ['num_preg', 'glucose_conc', 'diastolic_bp', 'thickness', 'bmi', 'insulin', 'diab_pred', 'age']
pred_col_names = ['diabetes']

#prepare feature and target values
x = df[feature_col_names].values
y = df[pred_col_names].values

#split the data into train and test
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)

print(f"Total number of training data is: {y_train.shape}")
print(f"Total number of testing is: {y_test.shape}")

clf = GaussianNB()
clf.fit(x_train, y_train)

#predictions
predicted = clf.predict(x_test)
predicted_test_data = clf.predict([[6, 148, 72, 35, 0, 33.6, 0.627, 50]])

print("Confusion matrix \n")
print(metrics.confusion_matrix(y_test, predicted))
print("Accuracy: \n")
print(metrics.accuracy_score(y_test, predicted))
print("Precision: \n")
print(metrics.precision_score(y_test, predicted))
print("Reccall: \n")
print(metrics.recall_score(y_test, predicted))
print("predicted value: ")
print(predicted_test_data)

Total number of training data is: (614, 1)
Total number of testing is: (154, 1)
Confusion matrix 

[[89 17]
 [23 25]]
Accuracy: 

0.7402597402597403
Precision: 

0.5952380952380952
Reccall: 

0.5208333333333334
predicted value: 
[0]


C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
